name: Deploy to GitHub

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-web:
    name: Deploy to Github
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setting up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter Version
        run: flutter --version

      - name: Cleaning Project
        run: flutter clean

      - name: Installing Dependencies
        run: flutter pub get

      - name: Creating a build
        run: flutter build web --release --base-href "/flutter-curve-visualizer/"

      - name: Deploying to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
